### ISSUE TITLE
create a document (markdown) that articulates the criteria for dataset validity

### ISSUE THREAD

**Issue by mbaljko** [LePa-YU/Datasets#2]
- create a markdown document that articulates the criteria for dataset validity (as a enumeration of bullet points)
- the visualizer requires the dataset to be valid (so it does not crap out)
- we need to add validation (e.g., anything in the main branch is assured to have been validated) 
- eventually this will be a tool, just get started with a requirements document to start with

**Comment by biltzerpos** [comment]
The document has been added to the root of the repo.
