### ISSUE TITLE
EECS 3461:  misplaced connection to start node

### ISSUE THREAD

**Issue by ElmiraOn** [LePa-YU/Datasets#7]
while checking the dataset for 3461 to fix the bug that caused a problem with Visualizer, I noticed that in the dataset node with id 1 is not connected to the start node properly through comesAfter. I believe that the id that was supposed to be in the comesAfter column for this node was entered in the assesses column by accident:

![image](https://user-images.githubusercontent.com/90576588/224224976-11a5a535-48f2-49e0-8528-5a74ee3b6059.png)

**Comment by ElmiraOn** [comment]
Also noticed similar issue in 4462 for start node where the type was added in comesAfter column

**Comment by biltzerpos** [comment]
Thanks Elmira, I think you are right. I'll ask Anni to confirm and fix.

**Comment by annisiren** [comment]
Yes this was a typo. Fixed. I'll push the changes soon.

**Comment by biltzerpos** [comment]
OK, please reply when the changes are pushed.

**Comment by biltzerpos** [comment]
Fixed. Closing.
